---
abstract: 'connect to HideMyAss.com (HMA) proxy servers using OpenVPN.'
author:
  - 'David Farrell <davidnmfarrell@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.130880'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-OpenVPN-ProxyManager-HMA
provides:
  Net::OpenVPN::ProxyManager::HMA:
    file: lib/Net/OpenVPN/ProxyManager/HMA.pm
    version: 0.03
requires:
  LWP::Simple: 6
  Moose: 2.0603
  Net::OpenVPN::ProxyManager: 0.03
  perl: v5.10.0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.03
